---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: chef/ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ssh-import-id::default]
    attributes:
      ssh_import_id:
        users:
          - name: vagrant
            github_accounts:
              - adamkrone
              - einsty
          - name: root
            github_accounts:
              - adamkrone
